import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: '10mb' }));

// Gemini Initialization
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

// API Routes
app.post("/api/avatar/generate", async (req, res) => {
  const { prompt, userInterests } = req.body;
  
  if (!process.env.GEMINI_API_KEY) {
    return res.status(500).json({ error: "Gemini API key is not configured" });
  }

  try {
    // Generate a creative avatar prompt based on interests
    const promptResponse = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: `Generate a detailed, single-paragraph artistic prompt for an AI image generator to create a professional academic avatar for a student researcher. 
      Interests: ${userInterests || 'Economics, Science'}. 
      Style requested: ${prompt || 'Modern 3D illustration'}. 
      The output should ONLY be the prompt string.`,
    });

    const refinedPrompt = promptResponse.text || prompt || "A professional 3D student avatar, academic style, economy theme";

    // Now generate the actual image
    const imageResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [{ text: refinedPrompt }],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1"
        }
      }
    });

    let base64Image = "";
    for (const part of imageResponse.candidates[0].content.parts) {
      if (part.inlineData) {
        base64Image = `data:image/png;base64,${part.inlineData.data}`;
        break;
      }
    }

    if (!base64Image) {
      throw new Error("No image was generated by the model");
    }

    res.json({ imageUrl: base64Image });
  } catch (error: any) {
    console.error("Avatar generation error:", error);
    res.status(500).json({ error: error.message || "Failed to generate avatar" });
  }
});

// Vite middleware setup
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
